#1#################################################
setwd("C:\\Users\\tinah\\OneDrive\\桌面\\成大\\科學計算機軟體\\C6\\C6_HW\\C6_HW")
getwd()
data1<-read.csv("C6_HW1.csv")
 
str(data1)
View(data1)
dim(data1)
aov1 <- aov(Yield~ factor(Brand_ID), data=data1)
summary(aov1)

data1<-read.csv("C6_HW2.csv")
str(data2)   
View(data2)		
dim(data2)
aov2 <- aov(Speed~ factor(Train_ID), data=data2) 
summary(aov2)
install.packages("car")
library(car)
leveneTest(data2$Speed, data2$Train_ID, center=mean)
install.packages("remotes")                          
library(remotes)
install_version("laercio","1.0.1")
LDuncan(aov2,"Train_ID") 
TukeyHSD(aov2) 
